### ISSUE TITLE
Some problems about svfinder work_on_collection

### ISSUE THREAD

**Issue by ShawRyu** [korem-lab/SGVFinder2#13]
I performed svfinder work_on_collection like this:
```
mkdir -p $wd/$job_pre.res/03.svfinder
mkdir -p $wd/$job_pre.res/03.svfinder/Bacterial_info
mkdir -p $wd/$job_pre.res/03.svfinder/SV_browser
nohup svfinder work_on_collection \
    --samp_to_map_dir $wd/$job_pre.res/01.icra_mapping/ \
    --max_spacing 10 \
    --x_coverage 0.01 \
    --rate_param 10 \
    --min_samp_cutoff 45 \
    --vsgv_dissim_thresh 0.125 \
    --dels_cooc_thresh 0.25 \
    --vsgv_clip_quantile 0.02 \
    --vsgv_fit_interval 0.95 \
    --browser_path $wd/$job_pre.res/03.svfinder/SV_browser \
    --bac_frames_path $wd/$job_pre.res/03.svfinder/Bacterial_info \
    --output_dsgv $wd/$job_pre.res/03.svfinder/dsgv_res.csv \
    --output_vsgv $wd/$job_pre.res/03.svfinder/vsgv_res.csv \
    --csv_output >/dev/null 2>sgvfinder.log &
```
**An error occurred only when the --browser_path was set.**
```
Traceback (most recent call last):
  File "/storage1/miniconda3/envs/SGVFinder2/bin/svfinder", line 8, in <module>
    sys.exit(run())
  File "/storage1/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/cli/svfinder_cli.py", line 95, in run
    vsgv, dsgv = work_on_collection(
  File "/storage1/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py", line 235, in work_on_collection
    draw_one_region(bacname, binsize, taxonomy, normdf,
  File "/storage1/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py", line 446, in draw_one_region
    p1 = bpl.figure(plot_width=1200, plot_height=400,
  File "/storage1/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/bokeh/plotting/_figure.py", line 192, in __init__
    self._raise_attribute_error_with_matches(name, names | opts.properties())
  File "/storage1/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/bokeh/core/has_props.py", line 368, in _raise_attribute_error_with_matches
    raise AttributeError(f"unexpected attribute {name!r} to {self.__class__.__name__}, {text} attributes are {nice_join(matches)}")
AttributeError: unexpected attribute 'plot_width' to figure, similar attributes are outer_width, width or min_width
```
**I inferred this is because the taxonomy and genepos files need to be included. How do I build the genepos.df and taxonomy.df files?**

**The warnings below were noisy despite not affecting eventual results.**
```
/storage1/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:269: FutureWarning: Returning a DataFrame from Series.apply when the supplied function returns a Series is deprecated and will be removed in a future version.
  dx = ndf.apply(dense_stats, args=(perc,), axis=1).apply(Series).rename(columns={0: 'mean', 1: 'std'})
/storage1/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf

/storage1/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/storage1/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)

```

**Comment by ym2877** [comment]
Hi @ShawRyu 

Thank you for bringing this to my attention! I believe this error was caused by an old version of the plotting library Bokeh. Please pull the fix I have made and give this another try.

**Comment by ShawRyu** [comment]
> Hi @ShawRyu
> 
> Thank you for bringing this to my attention! I believe this error was caused by an old version of the plotting library Bokeh. Please pull the fix I have made and give this another try.

Hi Yoli,

Thank you for your reply. I re-install SGVFinder2 via pip as this:
`pip install --force-reinstall --no-cache-dir git+https://github.com/korem-lab/SGVFinder2.git`
Retried the same command and met an new error:
```
Running SGVFinder `work_on_collection`...
Found 454 finished samples...
2024-03-15 09:58:31,931-WARNING: Could not load taxonomy file (db_path + '.taxonomy.df'.
doing var regions XXXXXXX
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf
/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py:268: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  ndf = nodeldf.rolling(slen, slen, axis=1).sum().iloc[:, (slen - 1)::slen] if slen > 1 else nodeldf
Traceback (most recent call last):
  File "/storage1/wangluyao/miniconda3/envs/SGVFinder2/bin/svfinder", line 8, in <module>
    sys.exit(run())
  File "/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/cli/svfinder_cli.py", line 95, in run
    vsgv, dsgv = work_on_collection(
  File "/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py", line 235, in work_on_collection
    draw_one_region(bacname, binsize, taxonomy, normdf,
  File "/storage1/wangluyao/miniconda3/envs/SGVFinder2/lib/python3.10/site-packages/SGVFinder2/svfinder.py", line 467, in draw_one_region
    locgeneposs = geneposs.loc[bacname]
AttributeError: 'NoneType' object has no attribute 'loc'
```
I think this should be related to the missing of genepos.df and taxonomy.df. Could you please tell me how to make both of them?
BTW, the noisy warnings are still there.
Thank you for your attention to this matter.

**Comment by ym2877** [comment]
Hi @ShawRyu I believe this is a bug on our part- HTML output is not currently supported. Try not setting the `--browser_path` param and this will default it to **None**

**Comment by ShawRyu** [comment]
Hi @ym2877 
It went smoothly without --browser_path. And I still wonder how I make genepos.df and taxonomy.df. Thanks a lot!

**Comment by talkorem** [comment]
We currently don't support creating these files for new databases and anticipate deprecating the browser_path completely. I apologize for the inconvenience. You can examine the structure of the default dataframes if you want to recreate them yourself.

**Comment by ShawRyu** [comment]
> We currently don't support creating these files for new databases and anticipate deprecating the browser_path completely. I apologize for the inconvenience. You can examine the structure of the default dataframes if you want to recreate them yourself.

I see. Thank you for your quick reply.
