### ISSUE TITLE
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False

### ISSUE THREAD

**Issue by JINCHENG-bio** [korem-lab/SGVFinder2#14]
Thank you for upgrading SGVFinder to allow the use of custom databases.
Unfortunately, I was stuck at an error for a long while, when running **ICRA**.
details as following:

```
Running ICRA on paired-end reads!
Forward- CLEAN_READS//R0025_1.fastq
Reverse- CLEAN_READS//R0025_2.fastq
--------------------------------------------

Traceback (most recent call last):
  File "/mnt/data/admin01/Public/metawrap/TIS_metagenomics_produced/SGVFinder2_res/ICRA.py", line 30, in <module>
    run_ICRA(reads1, reads2, outpath)
  File "/mnt/data/admin01/Public/metawrap/TIS_metagenomics_produced/SGVFinder2_res/ICRA.py", line 11, in run_ICRA
    jspi_file, jsdel_file = single_file(
  File "/mnt/data/admin01/Public/jcdai/miniconda3/envs/SGVfinder2/lib/python3.10/site-packages/SGVFinder2/icra.py", line 85, in single_file
    sam2pmp(outpref + '.bam', outpref + '.pmp', full=True)
  File "/mnt/data/admin01/Public/jcdai/miniconda3/envs/SGVfinder2/lib/python3.10/site-packages/SGVFinder2/helpers/ICRAUtils.py", line 23, in timed
    result = method(*args, **kw)
  File "/mnt/data/admin01/Public/jcdai/miniconda3/envs/SGVfinder2/lib/python3.10/site-packages/SGVFinder2/helpers/sam2pmp.py", line 23, in sam2pmp
    f = pysam.AlignmentFile(samfile)
  File "pysam/libcalignmentfile.pyx", line 748, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 997, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False
```

here is the code:

```
# step1 - Create DB
from SGVFinder2 import create_db_from_reps
create_db_from_reps(
    input_path='/SGVFinder2_res/db_input/',
    out_prefix='/SGVFinder2_res/custom_db/custom_db'
)

# step2 - Run ICRA
from SGVFinder2 import single_file, get_sample_map
from pandas import to_pickle

read1 = 'CLEAN_READS/R0025_1.fastq'
read2 = 'CLEAN_READS/R0025_2.fastq'

DATABASE = '/SGVFinder2_res/custom_db/custom_db'   ## I also tried this, but got the same error: DATABASE = '/SGVFinder2_res/custom_db/' 
jspi_file, jsdel_file = single_file(
    fq1=read1,
    fq2=read2,
    outfol='example_out/', 
    dbpath=DATABASE
)
sample_map = get_sample_map(jsdel_file,DATABASE+'.dlen') 
to_pickle(sample_map,jsdel_file.replace('.jsdel','.smp'))

```

The output files of step1:
 45M -rw-r--r-- 1 admin01 manager  45M Mar 23 13:51 custom_db.dests
266K -rw-r--r-- 1 admin01 manager 266K Mar 23 13:51 custom_db.dlen
 12G -rw-r--r-- 1 admin01 manager  12G Mar 23 13:51 custom_db.fasta
 35M -rw-r--r-- 1 admin01 manager  35M Mar 23 13:51 custom_db.lengths

It seems like it didn't align correctly or perhaps couldn't find the database. I've tried using some other samples as input and encountered the same error, resulting in identical BAM files of about 62 bytes (except for the name).

Hope you guys could help me out with this, I would be beyond grateful. 
Looking forward to your replies.

Best regards,
Jincheng

**Comment by talkorem** [comment]
Did you create a bowtie index?
bowtie2-build custom_db.fasta custom_db

**Comment by JINCHENG-bio** [comment]
Thanks, Dr. Korem!  That's the problem. It works like a charm now.

> Did you create a bowtie index? bowtie2-build custom_db.fasta custom_db
