### ISSUE TITLE
trouble  of ICRA

### ISSUE THREAD

**Issue by AmberCC15** [korem-lab/SGVFinder2#21]
Hi，I have encountered an issue while trying to use the single_file and get_sample_map functions from the SGVFinder2 module. When I attempt to run my script, I receive the following error message:Traceback (most recent call last):
  File "process_fastq.py", line 1, in <module>
    from SGVFinder2 import single_file, get_sample_map
  File "/data2/qiuli/meta/cebus/SGVFinder2.py", line 1, in <module>
    from SGVFinder2 import single_file, get_sample_map
ImportError: cannot import name 'single_file'

Here is the relevant portion of my script:
from SGVFinder2 import single_file, get_sample_map
from pandas import to_pickle

read1 = '/data2/qiuli/meta/cebus/SRR8101048_1.fastq'
read2 = '/data2/qiuli/meta/cebus/SRR8101048_2.fastq'

DATABASE = '/data2/qiuli/meta/SV/P1db'
jspi_file, jsdel_file = single_file(
    fq1=read1,
    fq2=read2,
    outfol='SRR8101048example_out/', 
    dbpath=DATABASE
)
sample_map = get_sample_map(jsdel_file, DATABASE + '.dlen') 
to_pickle(sample_map, jsdel_file.replace('.jsdel', '.smp'))

**Comment by ym2877** [comment]
How are you installing the package? Are you running `pip install --no-cache-dir git+https://github.com/korem-lab/SGVFinder2.git`? 

Also, make sure that you have the correct conda environment (the environment in which you pip installed the package) activated when you run your script.
