### ISSUE TITLE
Missing check that samtools and bowtie2 are installed

### ISSUE THREAD

**Issue by jiushao12345** [korem-lab/SGVFinder2#5]
Hello I got an error when I tried to run ICRA step. I confirm that the SGVFinder2 has been installed successfully in conda. 
I write the shell about icra --outfol ./test/test_1 \
     --fq1 1.fastq \
     --fq2 2.fastq \
     --db ./mpa_vJun23_CHOCOPhlAnSGB_202307
and it showed that Traceback (most recent call last):
  File "/**/minicoda3/envs/sgvfinder2/bin/icra", line 5, in <module>
    from SGVFinder2.cli.icra_cli import main
  File "/**/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/cli/icra_cli.py", line 37, in <module>
    jspi_file, jsdel_file = single_file(
  File "/**/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/icra.py", line 79, in single_file
    do_pair_simple(fq1, fq2, outpref, indexf, senspreset, report_alns, max_ins, threads)
  File "/**/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/helpers/Bowtie2WrapperSlim.py", line 25, in do_pair_simple
    dope(fq1, fq2, outprefix, indexf, True, False, senspreset, report_alns, 0, max_ins, True, True, False, False,
  File "/**/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/helpers/Bowtie2WrapperSlim.py", line 51, in dope
    _ = _shell_command(cmd, loglevel=logging.DEBUG)
  File "/**/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/helpers/ICRAUtils.py", line 95, in _shell_command
    errnout = sbcheck_output(com, shell=True, stderr=subprocess.STDOUT).decode(sys.stdout.encoding)
  File "/**/minicoda3/envs/sgvfinder2/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/**/minicoda3/envs/sgvfinder2/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bowtie2 -x /**/mpa_vJun23_CHOCOPhlAnSGB_202307 -1 /**/1.fastq -2 /**/2.fastq --very-sensitive -k 20  -I 0 -X 750 --no-mixed --no-discordant   --quiet -p 1 | samtools view -bS -@ 0 - > /**/test/test_1/**.bam' returned non-zero exit status 127.
I also run bowtie2 step, and the sam file was successfully obtained. So, I think my database folder in bowtie2 worked well. So, I want to know how to fix it.

**Comment by jiushao12345** [comment]
I solved the problem. There was no samtools software, so it cannot generate the bam file. I use  command  about "module load samtools" and this error disappeared

**Comment by talkorem** [comment]
Thanks @jiushao12345 . We'll add a specific check for this.

**Comment by jiushao12345** [comment]
Hello, I also met another problem about runing ICRA step.
2024-01-12 18:20:20,810-DEBUG: Loading database...
2024-01-12 18:20:20,810-DEBUG: Loaded. Mapping file...
2024-01-12 18:20:20,810-DEBUG: bowtie2 -x ./mpa_vJun23_CHOCOPhlAnSGB_202307 -1 1.fastq -2 2.fastq --very-sensitive -k 20  -I 0 -X 750 --no-mixed --no-discordant   --quiet -p 16.0 | samtools view -bS -@ 15.0 - > 1.bam

2024-01-12 23:40:51,912-DEBUG: Mapped. Converting to pmp
2024-01-12 23:48:34,881-DEBUG: Method 'sam2pmp' took 0:07:42.941190
2024-01-12 23:48:34,881-DEBUG: PMP ready. Running ICRA...
Traceback (most recent call last):
  File "/minicoda3/envs/sgvfinder2/bin/icra", line 5, in <module>
    from SGVFinder2.cli.icra_cli import main
  File "/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/cli/icra_cli.py", line 37, in <module>
    jspi_file, jsdel_file = single_file(
  File "/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/icra.py", line 94, in single_file
    _initialize(fq1, fq2, outpref + '.pmp', dlen_db_f, max_mismatch, consider_lengths, length_minimum,
  File "/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/helpers/ICRAUtils.py", line 23, in timed
    result = method(*args, **kw)
  File "/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/icra.py", line 147, in _initialize
    dest_dict = read_pickle(dest_dictf) if dest_dictf is not None else None
  File "/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/pandas/io/pickle.py", line 189, in read_pickle
    with get_handle(
  File "/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/pandas/io/common.py", line 872, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/metaphlan_databases/new_data/mpa_vJun23_CHOCOPhlAnSGB_202307.dests'
It seems that I didin't have the correct reference. So I run the prepare step and generate the refrence files:
mpa_vJun23_CHOCOPhlAnSGB_202307.1.bt2l  
mpa_vJun23_CHOCOPhlAnSGB_202307.dests    
mpa_vJun23_CHOCOPhlAnSGB_202307.rev.1.bt2l
mpa_vJun23_CHOCOPhlAnSGB_202307.2.bt2l  
mpa_vJun23_CHOCOPhlAnSGB_202307.dlen     
mpa_vJun23_CHOCOPhlAnSGB_202307.rev.2.bt2l
mpa_vJun23_CHOCOPhlAnSGB_202307.3.bt2l  
mpa_vJun23_CHOCOPhlAnSGB_202307.fasta
mpa_vJun23_CHOCOPhlAnSGB_202307.4.bt2l  
mpa_vJun23_CHOCOPhlAnSGB_202307.lengths
And I got an error about:
2024-01-14 05:27:03,613-DEBUG: PMP ready. Running ICRA...
2024-01-14 05:27:09,569-INFO: Average read length for 1.fastq set to 148
Traceback (most recent call last):
  File "/minicoda3/envs/sgvfinder2/bin/icra", line 5, in <module>
    from SGVFinder2.cli.icra_cli import main
  File "/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/cli/icra_cli.py", line 37, in <module>
    jspi_file, jsdel_file = single_file(
  File "/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/icra.py", line 94, in single_file
    _initialize(fq1, fq2, outpref + '.pmp', dlen_db_f, max_mismatch, consider_lengths, length_minimum,
  File "/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/helpers/ICRAUtils.py", line 23, in timed
    result = method(*args, **kw)
  File "/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/icra.py", line 154, in _initialize
    read_container.add_pmp_sr(sr, pe, allowed_dests, max_mismatch, None, dest_dict)
  File "/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/helpers/ReadContainer.py", line 80, in add_pmp_sr
    newdest, addpos = dest_dict[pemap.dest_id] if dest_dict is not None else (pemap.dest_id, 0)
KeyError: 'UniRef90_B0NE80|1__11|SGB4575'
I want to know how to fix it. 
Many thinks

**Comment by jiushao12345** [comment]
@talkorem

**Comment by talkorem** [comment]
We're working on solving this. In the future though, please open new issues for separate problems.

**Comment by jiushao12345** [comment]
Thank you, I have solved the problem of the refrence database.

**Comment by ym2877** [comment]
I have added appropriate checks that bowtie2 and samtools are installed. Will close this issue now.

**Comment by talkorem** [comment]
@jiushao12345 , one more comment - it seems that you're running ICRA on genes. That could work - but SGVFinder should not.

**Comment by jiushao12345** [comment]
Thank you

**Comment by jiushao12345** [comment]
@talkorem Thank you for your suggestion. I read the newest article in Nature (Host genetic regulation of human gut microbial structural variation). And I found the refrence database in proGenomes database (**http://progenomes1.embl.de/**). I thought the file (**representatives.contigs.fasta.gz**) was used for refrence database. I would like to ask if the refrence file is correct. looks for your help. Think your!

**Comment by talkorem** [comment]
This is the default reference database published with SGVFinder: https://github.com/segalab/SGVFinder#install
