### ISSUE TITLE
An error in /SGVFinder2/cli/icra_cli.py file

### ISSUE THREAD

**Issue by jiushao12345** [korem-lab/SGVFinder2#6]
I have already build the refrence database. And I got anther error in ICRA step.
It seems in the file (SGVFinder2/cli/icra_cli.py)
This is a detailed error report:
.....
2024-01-16 16:46:50,779-INFO: Average read length for re_SF00036388_1_kneaddata_paired.fastq set to 148
2024-01-16 16:47:18,356-DEBUG: Method '_get_unique_cov_dic' took 0:00:00.000015
2024-01-16 16:47:18,356-INFO: _initialize: Parameter init complete. Time: 0:00:33.966127
this is the len of delta:
0
Finished running ICRA, saving results to /Gut_SV/test/test_3
Traceback (most recent call last):
  File "/minicoda3/envs/sgvfinder2/bin/icra", line 5, in <module>
    from SGVFinder2.cli.icra_cli import main
  File "/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/cli/icra_cli.py", line 59, in <module>
    print('Running `get_sample_map` on %s, output will be saved to'%(jsdel_file,jsdel_file.replace('.jsdel','.smp')))
**TypeError: not all arguments converted during string formatting**
I check the icra_cli.py file, and I cannot found the command "import main"
I changed the command "print('Running `get_sample_map` on %s, output will be saved to'%(jsdel_file,jsdel_file.replace('.jsdel','.smp')))" to "print('Running `get_sample_map` on %s, output will be saved to **%s**'%(jsdel_file,jsdel_file.replace('.jsdel','.smp')))". 
And I run the ICRA step again.
This is the new error report:
2024-01-16 17:40:47,719-INFO: _initialize: Parameter init complete. Time: 0:00:31.487062
this is the len of delta:
0
Finished running ICRA, saving results to /Gut_SV/test/test_3
Running `get_sample_map` on /Gut_SV/test/test_3/re_SF00036388_1_kneaddata_paired.jsdel, output will be saved to /Gut_SV/test/test_3/re_SF00036388_1_kneaddata_paired.smp
Traceback (most recent call last):
  File "/storage/zhenghoufengLab/guanpenglin/minicoda3/envs/sgvfinder2/bin/icra", line 5, in <module>
    from SGVFinder2.cli.icra_cli import main
**ImportError: cannot import name 'main' from 'SGVFinder2.cli.icra_cli'** (/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/cli/icra_cli.py)
I think there was something wrong in python file (SGVFinder2/cli/icra_cli.py)
Thanks for your help.

**Comment by ym2877** [comment]
Hi @jiushao12345 please update the package to incorporate fix. Also note that you will need to install this package using `pip install` in order for these commands to work.

**Comment by jiushao12345** [comment]
Hi,@ym2877 It work well, thank you for your help. And I have another question now.
