### ISSUE TITLE
An error in svfinder work_on_collection step

### ISSUE THREAD

**Issue by jiushao12345** [korem-lab/SGVFinder2#7]
Hello, I have already generated smp file and no errors were reported.
Then, I run svfinder work_on_collection command and found the error
svfinder work_on_collection --samp_to_map_dir ./Rep_result/ \
>     --output_dsgv ./Rep_SVs/ \
>     --output_vsgv ./Rep_SVs/
Running SGVFinder `work_on_collection`...
Found 629 finished samples...
Traceback (most recent call last):
  File "/storage/zhenghoufengLab/guanpenglin/minicoda3/envs/sgvfinder2/bin/svfinder", line 8, in <module>
    sys.exit(run())
  File "/storage/zhenghoufengLab/guanpenglin/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/cli/svfinder_cli.py", line 113, in run
    if args.csv_output:
AttributeError: 'Namespace' object has no attribute 'csv_output'
I try to run the python file:
from SGVFinder2 import work_on_collection
vsgv, dsgv = work_on_collection(
    samp_to_map='./Rep_result/',
    max_spacing=10,
    min_samp_cutoff=2, 
    delsdetectthresh=0.25, 
    real_del_thresh=0.95, 
    dels_cooc_thresh=0.25,
    vsgv_dissim_thresh=0.125, 
    vsgv_clip_quantile=0.02, 
    vsgv_fit_interval=0.95, 
    vsgv_fit_method='betaprime',
    x_coverage=0.01,
    rate_param=10, 
    vsgv_dense_perc=85, 
    browser_path=None, 
    frames_path=None
)
vsgv.to_csv('./vsgv_test.csv')
dsgv.to_csv(.'/dsgv_test.csv')
I did get two csv file with nothing.(The file only has two quotes, just like "")
Looks for your help, thank you.
I also found my smp , jspi and jsdel files were too small (less than 1 kb):
13922522014 Jan 22 17:48 re_478180_1_kneaddata_paired.bam
69 Jan 22 20:29 re_478180_1_kneaddata_paired.jsdel
62 Jan 22 20:29 re_478180_1_kneaddata_paired.jspi
10740445117 Jan 22 20:18 re_478180_1_kneaddata_paired.pmp
5 Jan 22 20:29 re_478180_1_kneaddata_paired.smp
I try to use several bowtie2 reference database and have the similar results (less than 1 kb). I wonder if this is right.

**Comment by ym2877** [comment]
My apologies for the delay @jiushao12345! I just updated with a fix.

**Comment by jiushao12345** [comment]
hi, @ym2877, thanks for your reply.  I reinstall svfinder2. And I found another question.
I use the command "svfinder work_on_collection --help" and found the errors:
Traceback (most recent call last):
  File "/storage/zhenghoufengLab/guanpenglin/minicoda3/envs/sgvfinder2/bin/svfinder", line 5, in <module>
    from SGVFinder2.cli.svfinder_cli import run
  File "/storage/zhenghoufengLab/guanpenglin/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/__init__.py", line 3, in <module>
    from .createdb import create_db_from_reps
  File "/storage/zhenghoufengLab/guanpenglin/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/createdb.py", line 10, in <module>
    from ICRAUtils import _open_gz_indif, _set_logging_handlers
**ModuleNotFoundError: No module named 'ICRAUtils'**
And I use the command "icra --help" there was also the same error.
Traceback (most recent call last):
  File "/storage/zhenghoufengLab/guanpenglin/minicoda3/envs/sgvfinder2/bin/icra", line 5, in <module>
    from SGVFinder2.cli.icra_cli import run
  File "/storage/zhenghoufengLab/guanpenglin/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/__init__.py", line 3, in <module>
    from .createdb import create_db_from_reps
  File "/storage/zhenghoufengLab/guanpenglin/minicoda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/createdb.py", line 10, in <module>
    from ICRAUtils import _open_gz_indif, _set_logging_handlers
**ModuleNotFoundError: No module named 'ICRAUtils'**

**Comment by ym2877** [comment]
@jiushao12345 my apologies- fixed this issue as well.
